//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeOdev.Yonetim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galeri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Galeri()
        {
            this.Sorular = new HashSet<Sorular>();
        }
    
        public int Id { get; set; }
        public string Link { get; set; }
        public string PicUrl { get; set; }
        public Nullable<bool> Sil { get; set; }
        public Nullable<int> GaleriTur { get; set; }
    
        public virtual GaleriTur GaleriTur1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sorular> Sorular { get; set; }
    }
}
